# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  main:
  - name: Bio
    url: /
    weight: 10
  - name: Papers
    url: /#papers
    weight: 11
  - name: Talks
    url: /#talks
    weight: 12
  - name: News
    url: /#news
    weight: 13
  - name: Experience
    url: experience/
    weight: 20

# Uncomment the lines below to configure your website in a second language.
ru:
  languageCode: ru-RU
  contentDir: content/ru
  title: Резюме Анны Живцовой
  params:
    description: Резюме Анны Живцовой
  main:
  - name: Основные сведения
    url: /
    weight: 20
  - name: Публикации
    url: /publications/_index/
    weight: 21
  - name: Выступления
    url: events/_index/
    weight: 22
  - name: Новости
    url: /posts
    weight: 23
  - name: Опыт
    url: experience/
    weight: 30

  #menu:
  #  main:
  #  - name: Основные сведения
  #    url: /
  #    weight: 20
  #  - name: Публикации
  #    url: publications/_index
  #    weight: 21
  #  - name: Выступления
  #    url: events/_index
  #    weight: 22
  #  - name: Новости
  #    url: post/_index
  #    weight: 23
  #  - name: Опыт
  #    url: experience/
  #    weight: 30
